// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydvgnptdqnqxmueflhxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkdmducHRkcW5xeG11ZWZsaHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjM4MjYsImV4cCI6MjA2Mzg5OTgyNn0.2H278Kv-vfPdpkBxohqj9t5HdOJfKBakFF0XZIEcaEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);